version: '3.8'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service-container
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .env:/app/.env
    networks:
      - backend

  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb-container
    networks:
      - backend

networks:
  backend:
    external: true
