version: '3.8'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service-container
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
#    environment:
#      - ATLAS_URI=mongodb://mongodb:27017
#      - DB_NAME=pymongo
    volumes:
      - .env:/app/.env
    networks:
      - backend

  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb-container
    networks:
      - backend

networks:
  backend:
    external: true
